export const COUNTRIES = [
  {"name":"Afghanistan","iso":"AF","tld":".af"},
  {"name":"Albania","iso":"AL","tld":".al"},
  {"name":"Algeria","iso":"DZ","tld":".dz"},
  {"name":"American Samoa","iso":"AS","tld":".as"},
  {"name":"Andorra","iso":"AD","tld":".ad"},
  {"name":"Angola","iso":"AO","tld":".ao"},
  {"name":"Anguilla","iso":"AI","tld":".ai"},
  {"name":"Antarctica","iso":"AQ","tld":".aq"},
  {"name":"Antigua and Barbuda","iso":"AG","tld":".ag"},
  {"name":"Argentina","iso":"AR","tld":".ar"},
  {"name":"Armenia","iso":"AM","tld":".am"},
  {"name":"Aruba","iso":"AW","tld":".aw"},
  {"name":"Australia","iso":"AU","tld":".au"},
  {"name":"Austria","iso":"AT","tld":".at"},
  {"name":"Azerbaijan","iso":"AZ","tld":".az"},
  {"name":"Bahamas","iso":"BS","tld":".bs"},
  {"name":"Bahrain","iso":"BH","tld":".bh"},
  {"name":"Bangladesh","iso":"BD","tld":".bd"},
  {"name":"Barbados","iso":"BB","tld":".bb"},
  {"name":"Belarus","iso":"BY","tld":".by"},
  {"name":"Belgium","iso":"BE","tld":".be"},
  {"name":"Belize","iso":"BZ","tld":".bz"},
  {"name":"Benin","iso":"BJ","tld":".bj"},
  {"name":"Bermuda","iso":"BM","tld":".bm"},
  {"name":"Bhutan","iso":"BT","tld":".bt"},
  {"name":"Bolivia","iso":"BO","tld":".bo"},
  {"name":"Bosnia and Herzegovina","iso":"BA","tld":".ba"},
  {"name":"Botswana","iso":"BW","tld":".bw"},
  {"name":"Brazil","iso":"BR","tld":".br"},
  {"name":"British Indian Ocean Territory","iso":"IO","tld":".io"},
  {"name":"Brunei","iso":"BN","tld":".bn"},
  {"name":"Bulgaria","iso":"BG","tld":".bg"},
  {"name":"Burkina Faso","iso":"BF","tld":".bf"},
  {"name":"Burundi","iso":"BI","tld":".bi"},
  {"name":"Cambodia","iso":"KH","tld":".kh"},
  {"name":"Cameroon","iso":"CM","tld":".cm"},
  {"name":"Canada","iso":"CA","tld":".ca"},
  {"name":"Cape Verde","iso":"CV","tld":".cv"},
  {"name":"Cayman Islands","iso":"KY","tld":".ky"},
  {"name":"Central African Republic","iso":"CF","tld":".cf"},
  {"name":"Chad","iso":"TD","tld":".td"},
  {"name":"Chile","iso":"CL","tld":".cl"},
  {"name":"China","iso":"CN","tld":".cn"},
  {"name":"Christmas Island","iso":"CX","tld":".cx"},
  {"name":"Cocos Islands","iso":"CC","tld":".cc"},
  {"name":"Colombia","iso":"CO","tld":".co"},
  {"name":"Comoros","iso":"KM","tld":".km"},
  {"name":"Congo","iso":"CG","tld":".cg"},
  {"name":"DR Congo","iso":"CD","tld":".cd"},
  {"name":"Cook Islands","iso":"CK","tld":".ck"},
  {"name":"Costa Rica","iso":"CR","tld":".cr"},
  {"name":"Croatia","iso":"HR","tld":".hr"},
  {"name":"Cuba","iso":"CU","tld":".cu"},
  {"name":"Cyprus","iso":"CY","tld":".cy"},
  {"name":"Czechia","iso":"CZ","tld":".cz"},
  {"name":"Denmark","iso":"DK","tld":".dk"},
  {"name":"Djibouti","iso":"DJ","tld":".dj"},
  {"name":"Dominica","iso":"DM","tld":".dm"},
  {"name":"Dominican Republic","iso":"DO","tld":".do"},
  {"name":"Ecuador","iso":"EC","tld":".ec"},
  {"name":"Egypt","iso":"EG","tld":".eg"},
  {"name":"El Salvador","iso":"SV","tld":".sv"},
  {"name":"Equatorial Guinea","iso":"GQ","tld":".gq"},
  {"name":"Eritrea","iso":"ER","tld":".er"},
  {"name":"Estonia","iso":"EE","tld":".ee"},
  {"name":"Eswatini","iso":"SZ","tld":".sz"},
  {"name":"Ethiopia","iso":"ET","tld":".et"},
  {"name":"Fiji","iso":"FJ","tld":".fj"},
  {"name":"Finland","iso":"FI","tld":".fi"},
  {"name":"France","iso":"FR","tld":".fr"},
  {"name":"Gabon","iso":"GA","tld":".ga"},
  {"name":"Gambia","iso":"GM","tld":".gm"},
  {"name":"Georgia","iso":"GE","tld":".ge"},
  {"name":"Germany","iso":"DE","tld":".de"},
  {"name":"Ghana","iso":"GH","tld":".gh"},
  {"name":"Gibraltar","iso":"GI","tld":".gi"},
  {"name":"Greece","iso":"GR","tld":".gr"},
  {"name":"Greenland","iso":"GL","tld":".gl"},
  {"name":"Grenada","iso":"GD","tld":".gd"},
  {"name":"Guam","iso":"GU","tld":".gu"},
  {"name":"Guatemala","iso":"GT","tld":".gt"},
  {"name":"Guernsey","iso":"GG","tld":".gg"},
  {"name":"Guinea","iso":"GN","tld":".gn"},
  {"name":"Guinea-Bissau","iso":"GW","tld":".gw"},
  {"name":"Guyana","iso":"GY","tld":".gy"},
  {"name":"Haiti","iso":"HT","tld":".ht"},
  {"name":"Honduras","iso":"HN","tld":".hn"},
  {"name":"Hong Kong","iso":"HK","tld":".hk"},
  {"name":"Hungary","iso":"HU","tld":".hu"},
  {"name":"Iceland","iso":"IS","tld":".is"},
  {"name":"India","iso":"IN","tld":".in"},
  {"name":"Indonesia","iso":"ID","tld":".id"},
  {"name":"Iran","iso":"IR","tld":".ir"},
  {"name":"Iraq","iso":"IQ","tld":".iq"},
  {"name":"Ireland","iso":"IE","tld":".ie"},
  {"name":"Isle of Man","iso":"IM","tld":".im"},
  {"name":"Israel","iso":"IL","tld":".il"},
  {"name":"Italy","iso":"IT","tld":".it"},
  {"name":"Jamaica","iso":"JM","tld":".jm"},
  {"name":"Japan","iso":"JP","tld":".jp"},
  {"name":"Jersey","iso":"JE","tld":".je"},
  {"name":"Jordan","iso":"JO","tld":".jo"},
  {"name":"Kazakhstan","iso":"KZ","tld":".kz"},
  {"name":"Kenya","iso":"KE","tld":".ke"},
  {"name":"Kiribati","iso":"KI","tld":".ki"},
  {"name":"Kuwait","iso":"KW","tld":".kw"},
  {"name":"Kyrgyzstan","iso":"KG","tld":".kg"},
  {"name":"Laos","iso":"LA","tld":".la"},
  {"name":"Latvia","iso":"LV","tld":".lv"},
  {"name":"Lebanon","iso":"LB","tld":".lb"},
  {"name":"Lesotho","iso":"LS","tld":".ls"},
  {"name":"Liberia","iso":"LR","tld":".lr"},
  {"name":"Libya","iso":"LY","tld":".ly"},
  {"name":"Liechtenstein","iso":"LI","tld":".li"},
  {"name":"Lithuania","iso":"LT","tld":".lt"},
  {"name":"Luxembourg","iso":"LU","tld":".lu"},
  {"name":"Macau","iso":"MO","tld":".mo"},
  {"name":"Madagascar","iso":"MG","tld":".mg"},
  {"name":"Malawi","iso":"MW","tld":".mw"},
  {"name":"Malaysia","iso":"MY","tld":".my"},
  {"name":"Maldives","iso":"MV","tld":".mv"},
  {"name":"Mali","iso":"ML","tld":".ml"},
  {"name":"Malta","iso":"MT","tld":".mt"},
  {"name":"Marshall Islands","iso":"MH","tld":".mh"},
  {"name":"Mauritania","iso":"MR","tld":".mr"},
  {"name":"Mauritius","iso":"MU","tld":".mu"},
  {"name":"Mexico","iso":"MX","tld":".mx"},
  {"name":"Micronesia","iso":"FM","tld":".fm"},
  {"name":"Moldova","iso":"MD","tld":".md"},
  {"name":"Monaco","iso":"MC","tld":".mc"},
  {"name":"Mongolia","iso":"MN","tld":".mn"},
  {"name":"Montenegro","iso":"ME","tld":".me"},
  {"name":"Morocco","iso":"MA","tld":".ma"},
  {"name":"Mozambique","iso":"MZ","tld":".mz"},
  {"name":"Namibia","iso":"NA","tld":".na"},
  {"name":"Nauru","iso":"NR","tld":".nr"},
  {"name":"Nepal","iso":"NP","tld":".np"},
  {"name":"Netherlands","iso":"NL","tld":".nl"},
  {"name":"New Zealand","iso":"NZ","tld":".nz"},
  {"name":"Nicaragua","iso":"NI","tld":".ni"},
  {"name":"Niger","iso":"NE","tld":".ne"},
  {"name":"Nigeria","iso":"NG","tld":".ng"},
  {"name":"North Korea","iso":"KP","tld":".kp"},
  {"name":"North Macedonia","iso":"MK","tld":".mk"},
  {"name":"Norway","iso":"NO","tld":".no"},
  {"name":"Oman","iso":"OM","tld":".om"},
  {"name":"Pakistan","iso":"PK","tld":".pk"},
  {"name":"Palau","iso":"PW","tld":".pw"},
  {"name":"Panama","iso":"PA","tld":".pa"},
  {"name":"Papua New Guinea","iso":"PG","tld":".pg"},
  {"name":"Paraguay","iso":"PY","tld":".py"},
  {"name":"Peru","iso":"PE","tld":".pe"},
  {"name":"Philippines","iso":"PH","tld":".ph"},
  {"name":"Poland","iso":"PL","tld":".pl"},
  {"name":"Portugal","iso":"PT","tld":".pt"},
  {"name":"Qatar","iso":"QA","tld":".qa"},
  {"name":"Romania","iso":"RO","tld":".ro"},
  {"name":"Russia","iso":"RU","tld":".ru"},
  {"name":"Saudi Arabia","iso":"SA","tld":".sa"},
  {"name":"Senegal","iso":"SN","tld":".sn"},
  {"name":"Serbia","iso":"RS","tld":".rs"},
  {"name":"Singapore","iso":"SG","tld":".sg"},
  {"name":"Slovakia","iso":"SK","tld":".sk"},
  {"name":"Slovenia","iso":"SI","tld":".si"},
  {"name":"Somalia","iso":"SO","tld":".so"},
  {"name":"South Africa","iso":"ZA","tld":".za"},
  {"name":"South Korea","iso":"KR","tld":".kr"},
  {"name":"Spain","iso":"ES","tld":".es"},
  {"name":"Sri Lanka","iso":"LK","tld":".lk"},
  {"name":"Sudan","iso":"SD","tld":".sd"},
  {"name":"Sweden","iso":"SE","tld":".se"},
  {"name":"Switzerland","iso":"CH","tld":".ch"},
  {"name":"Syria","iso":"SY","tld":".sy"},
  {"name":"Taiwan","iso":"TW","tld":".tw"},
  {"name":"Tanzania","iso":"TZ","tld":".tz"},
  {"name":"Thailand","iso":"TH","tld":".th"},
  {"name":"Tunisia","iso":"TN","tld":".tn"},
  {"name":"Turkey","iso":"TR","tld":".tr"},
  {"name":"Ukraine","iso":"UA","tld":".ua"},
  {"name":"United Arab Emirates","iso":"AE","tld":".ae"},
  {"name":"United Kingdom","iso":"GB","tld":".uk"},
  {"name":"United States","iso":"US","tld":".us"},
  {"name":"Uruguay","iso":"UY","tld":".uy"},
  {"name":"Uzbekistan","iso":"UZ","tld":".uz"},
  {"name":"Vanuatu","iso":"VU","tld":".vu"},
  {"name":"Vatican City","iso":"VA","tld":".va"},
  {"name":"Venezuela","iso":"VE","tld":".ve"},
  {"name":"Vietnam","iso":"VN","tld":".vn"},
  {"name":"Yemen","iso":"YE","tld":".ye"},
  {"name":"Zambia","iso":"ZM","tld":".zm"},
  {"name":"Zimbabwe","iso":"ZW","tld":".zw"}
];

export const TLDS = [
  ".com", ".org", ".net", ".info", ".biz", ".name", ".pro", ".xyz", ".online", ".site", ".tech", ".store", ".blog", ".app", ".dev", ".ai", ".io", ".co", ".me", ".cc", ".tv",
  ".us", ".uk", ".ca", ".au", ".in", ".pk", ".bd", ".sa", ".ae", ".de", ".fr", ".it", ".es", ".nl", ".se", ".no", ".fi", ".dk", ".ch", ".ru", ".cn", ".jp", ".kr", ".br", ".mx", ".za", ".ng", ".eg", ".tr", ".id", ".my", ".sg", ".hk", ".nz",
  ".edu", ".gov", ".mil", ".int", ".aero", ".jobs", ".museum", ".travel", ".post", ".bank", ".insurance",
  ".cloud", ".digital", ".network", ".systems", ".solutions", ".tools", ".space", ".world", ".today", ".live", ".media", ".agency", ".company"
];

export const CATEGORIES = [
  "Business", "Ecommerce", "Technology", "SaaS", "Startups", "Finance", "Banking", "Insurance", "Cryptocurrency", "Real Estate", "Education", "Online Courses", "Jobs", "Recruitment", "Healthcare", "Medical", "Pharmacy", "Fitness", "Food", "Restaurants", "Travel", "Tourism", "Hotels", "Transportation", "Automotive", "Legal", "Law Firms", "Government", "Nonprofit", "News", "Media", "Entertainment", "Movies", "Music", "Gaming", "Sports", "Fashion", "Beauty", "Lifestyle", "Blogging", "Personal Websites", "Forums", "Communities", "Social Networks", "Marketing", "Advertising", "SEO", "Digital Agencies", "Freelancing", "Photography", "Design", "Architecture", "Construction", "Manufacturing", "Industrial", "Agriculture", "Energy", "Environment", "Pets", "Parenting", "Dating", "Events", "Religion", "Adult"
];
